version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: whatif
      POSTGRES_PASSWORD: whatif
      POSTGRES_DB: whatif
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
